Repository openshift/vsphere-problem-detector, pull requests merged in 2022-02, with the labels that each got.

#73 Bug 2051881: Dont forget to register metrics before emitting
  pkg/check/count_pv_types.go
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm, qe-approved

#74 Bug 2052609: Dont forget to register metrics before emitting
  pkg/check/count_pv_types.go
Labels: bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, approved, lgtm, backport-risk-assessed

#75 Bug 2055729: change NodePerfCheck criteria to be based on average latency
  pkg/check/node_perf.go
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm
